// Who wrote each book — shown under the chapter heading in the reader.
// Only books where a name can honestly be given appear here — genuinely
// anonymous books (Hebrews, Job, Esther, Judges, Kings, Chronicles, Ruth,
// Samuel, Lamentations, Jonah) are deliberately absent; the reader shows
// nothing rather than a guess. "Traditionally" marks attributions that rest
// on tradition rather than the text itself.
export const BOOK_AUTHORS = {
  GEN: 'Traditionally attributed to Moses',
  EXO: 'Traditionally attributed to Moses',
  LEV: 'Traditionally attributed to Moses',
  NUM: 'Traditionally attributed to Moses',
  DEU: 'Traditionally attributed to Moses',
  JOS: 'Traditionally attributed to Joshua',
  EZR: 'Traditionally attributed to Ezra',
  NEH: 'The memoirs of Nehemiah',
  PSA: 'Many authors — about half attributed to David',
  PRO: 'Mainly Solomon, with sayings of Agur and Lemuel',
  ECC: 'Traditionally attributed to Solomon, "the Teacher"',
  SNG: 'Traditionally attributed to Solomon',
  ISA: 'The prophet Isaiah',
  JER: 'The prophet Jeremiah',
  EZK: 'The prophet Ezekiel',
  DAN: 'Traditionally attributed to Daniel',
  HOS: 'The prophet Hosea',
  JOL: 'The prophet Joel',
  AMO: 'The prophet Amos',
  OBA: 'The prophet Obadiah',
  MIC: 'The prophet Micah',
  NAM: 'The prophet Nahum',
  HAB: 'The prophet Habakkuk',
  ZEP: 'The prophet Zephaniah',
  HAG: 'The prophet Haggai',
  ZEC: 'The prophet Zechariah',
  MAL: 'The prophet Malachi',
  MAT: 'Traditionally attributed to Matthew the apostle',
  MRK: "Traditionally attributed to Mark, Peter's companion",
  LUK: 'Traditionally attributed to Luke the physician',
  JHN: 'Traditionally attributed to John the apostle',
  ACT: 'Traditionally attributed to Luke the physician',
  ROM: 'Paul the apostle',
  '1CO': 'Paul the apostle',
  '2CO': 'Paul the apostle',
  GAL: 'Paul the apostle',
  EPH: 'Paul the apostle',
  PHP: 'Paul the apostle',
  COL: 'Paul the apostle',
  '1TH': 'Paul the apostle',
  '2TH': 'Paul the apostle',
  '1TI': 'Paul the apostle',
  '2TI': 'Paul the apostle',
  TIT: 'Paul the apostle',
  PHM: 'Paul the apostle',
  JAS: 'Traditionally James, brother of Jesus',
  '1PE': 'Peter the apostle',
  '2PE': 'Peter the apostle',
  '1JN': 'Traditionally attributed to John the apostle',
  '2JN': 'Traditionally attributed to John the apostle',
  '3JN': 'Traditionally attributed to John the apostle',
  JUD: 'Jude, brother of James',
  REV: 'John, writing from Patmos — traditionally the apostle',
};
