export const DAILY_VERSES = [
  { text: 'Come to me, all you who are weary and burdened, and I will give you rest.', ref: 'Matthew 11:28' },
  { text: 'The Lord is my shepherd; I shall not want.', ref: 'Psalm 23:1' },
  { text: 'Be still, and know that I am God.', ref: 'Psalm 46:10' },
  { text: 'Cast all your anxiety on him, because he cares for you.', ref: '1 Peter 5:7' },
  { text: 'Trust in the Lord with all your heart, and lean not on your own understanding.', ref: 'Proverbs 3:5' },
  { text: 'For I know the plans I have for you — plans to prosper you and not to harm you, plans to give you hope and a future.', ref: 'Jeremiah 29:11' },
  { text: 'And we know that in all things God works for the good of those who love him.', ref: 'Romans 8:28' },
  { text: 'Those who hope in the Lord will renew their strength. They will soar on wings like eagles.', ref: 'Isaiah 40:31' },
  { text: 'His mercies are new every morning; great is your faithfulness.', ref: 'Lamentations 3:22–23' },
  { text: 'I am the way, the truth, and the life.', ref: 'John 14:6' },
  { text: 'Do not be anxious about anything, but in every situation, by prayer and petition, present your requests to God.', ref: 'Philippians 4:6' },
  { text: 'The peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.', ref: 'Philippians 4:7' },
  { text: 'If God is for us, who can be against us?', ref: 'Romans 8:31' },
  { text: 'Be strong and courageous. Do not be afraid; the Lord your God will be with you wherever you go.', ref: 'Joshua 1:9' },
  { text: 'For God so loved the world that he gave his one and only Son.', ref: 'John 3:16' },
  { text: 'Therefore, if anyone is in Christ, the new creation has come: the old has gone, the new is here.', ref: '2 Corinthians 5:17' },
  { text: 'For we walk by faith, not by sight.', ref: '2 Corinthians 5:7' },
  { text: 'The Lord is my light and my salvation — whom shall I fear?', ref: 'Psalm 27:1' },
  { text: 'Delight yourself in the Lord, and he will give you the desires of your heart.', ref: 'Psalm 37:4' },
  { text: 'Weeping may stay for the night, but rejoicing comes in the morning.', ref: 'Psalm 30:5' },
  { text: 'Your word is a lamp for my feet, a light on my path.', ref: 'Psalm 119:105' },
  { text: 'He heals the brokenhearted and binds up their wounds.', ref: 'Psalm 147:3' },
  { text: 'Ask and it will be given to you; seek and you will find; knock and the door will be opened.', ref: 'Matthew 7:7' },
  { text: 'Love is patient, love is kind. It does not envy, it does not boast.', ref: '1 Corinthians 13:4' },
  { text: 'Above all, love each other deeply, because love covers over a multitude of sins.', ref: '1 Peter 4:8' },
  { text: 'Now faith is confidence in what we hope for and assurance about what we do not see.', ref: 'Hebrews 11:1' },
  { text: 'I have told you these things, so that in me you may have peace. Take heart — I have overcome the world.', ref: 'John 16:33' },
  { text: 'There is now no condemnation for those who are in Christ Jesus.', ref: 'Romans 8:1' },
  { text: 'For by grace you have been saved through faith — and this is not your own doing; it is the gift of God.', ref: 'Ephesians 2:8' },
  { text: 'I sought the Lord, and he answered me; he delivered me from all my fears.', ref: 'Psalm 34:4' },
  { text: 'The Lord is close to the brokenhearted and saves those who are crushed in spirit.', ref: 'Psalm 34:18' },
  { text: 'Surely your goodness and love will follow me all the days of my life.', ref: 'Psalm 23:6' },
  { text: 'He has made everything beautiful in its time.', ref: 'Ecclesiastes 3:11' },
  { text: 'Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.', ref: 'Galatians 6:9' },
  { text: 'The Lord your God is with you, the Mighty Warrior who saves.', ref: 'Zephaniah 3:17' },
  { text: 'Blessed are the pure in heart, for they will see God.', ref: 'Matthew 5:8' },
  { text: 'Greater love has no one than this: to lay down one’s life for one’s friends.', ref: 'John 15:13' },
  { text: 'Cast your cares on the Lord and he will sustain you.', ref: 'Psalm 55:22' },
  { text: 'He gives strength to the weary and increases the power of the weak.', ref: 'Isaiah 40:29' },
  { text: 'I can do all things through Christ who strengthens me.', ref: 'Philippians 4:13' },

  // ── Peace & rest ────────────────────────────────────────────────────────────
  { text: 'Peace I leave with you; my peace I give you. Do not let your hearts be troubled and do not be afraid.', ref: 'John 14:27' },
  { text: 'You will keep in perfect peace those whose minds are steadfast, because they trust in you.', ref: 'Isaiah 26:3' },
  { text: 'In peace I will lie down and sleep, for you alone, Lord, make me dwell in safety.', ref: 'Psalm 4:8' },
  { text: 'Truly my soul finds rest in God; my salvation comes from him.', ref: 'Psalm 62:1' },
  { text: 'When anxiety was great within me, your consolation brought me joy.', ref: 'Psalm 94:19' },
  { text: 'Therefore do not worry about tomorrow, for tomorrow will worry about itself.', ref: 'Matthew 6:34' },
  { text: 'Let the peace of Christ rule in your hearts, since as members of one body you were called to peace.', ref: 'Colossians 3:15' },
  { text: 'Return to your rest, my soul, for the Lord has been good to you.', ref: 'Psalm 116:7' },

  // ── Fear & courage ──────────────────────────────────────────────────────────
  { text: 'So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you.', ref: 'Isaiah 41:10' },
  { text: 'For I am the Lord your God who takes hold of your right hand and says to you, Do not fear; I will help you.', ref: 'Isaiah 41:13' },
  { text: 'When I am afraid, I put my trust in you.', ref: 'Psalm 56:3' },
  { text: 'For God has not given us a spirit of fear, but of power and of love and of a sound mind.', ref: '2 Timothy 1:7' },
  { text: 'Be strong and take heart, all you who hope in the Lord.', ref: 'Psalm 31:24' },
  { text: 'The Lord himself goes before you and will be with you; he will never leave you nor forsake you.', ref: 'Deuteronomy 31:8' },
  { text: 'Even though I walk through the darkest valley, I will fear no evil, for you are with me.', ref: 'Psalm 23:4' },
  { text: 'There is no fear in love. But perfect love drives out fear.', ref: '1 John 4:18' },

  // ── Strength ────────────────────────────────────────────────────────────────
  { text: 'The Lord is my strength and my shield; my heart trusts in him, and he helps me.', ref: 'Psalm 28:7' },
  { text: 'The Lord is my rock, my fortress and my deliverer.', ref: 'Psalm 18:2' },
  { text: 'The joy of the Lord is your strength.', ref: 'Nehemiah 8:10' },
  { text: 'Be strong in the Lord and in his mighty power.', ref: 'Ephesians 6:10' },
  { text: 'God is our refuge and strength, an ever-present help in trouble.', ref: 'Psalm 46:1' },
  { text: 'The Sovereign Lord is my strength; he makes my feet like the feet of a deer.', ref: 'Habakkuk 3:19' },
  { text: 'My flesh and my heart may fail, but God is the strength of my heart and my portion forever.', ref: 'Psalm 73:26' },

  // ── Hope ────────────────────────────────────────────────────────────────────
  { text: 'May the God of hope fill you with all joy and peace as you trust in him.', ref: 'Romans 15:13' },
  { text: 'And hope does not put us to shame, because God’s love has been poured out into our hearts.', ref: 'Romans 5:5' },
  { text: 'Be joyful in hope, patient in affliction, faithful in prayer.', ref: 'Romans 12:12' },
  { text: 'I wait for the Lord, my whole being waits, and in his word I put my hope.', ref: 'Psalm 130:5' },
  { text: 'See, I am doing a new thing! Now it springs up; do you not perceive it?', ref: 'Isaiah 43:19' },
  { text: 'But blessed is the one who trusts in the Lord, whose confidence is in him.', ref: 'Jeremiah 17:7' },
  { text: 'But now, Lord, what do I look for? My hope is in you.', ref: 'Psalm 39:7' },

  // ── Love & grace ────────────────────────────────────────────────────────────
  { text: 'We love because he first loved us.', ref: '1 John 4:19' },
  { text: 'But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.', ref: 'Romans 5:8' },
  { text: 'Neither death nor life will be able to separate us from the love of God that is in Christ Jesus our Lord.', ref: 'Romans 8:38–39' },
  { text: 'And now these three remain: faith, hope and love. But the greatest of these is love.', ref: '1 Corinthians 13:13' },
  { text: 'My grace is sufficient for you, for my power is made perfect in weakness.', ref: '2 Corinthians 12:9' },
  { text: 'He saved us, not because of righteous things we had done, but because of his mercy.', ref: 'Titus 3:5' },
  { text: 'How priceless is your unfailing love, O God! People take refuge in the shadow of your wings.', ref: 'Psalm 36:7' },
  { text: 'A new command I give you: Love one another. As I have loved you, so you must love one another.', ref: 'John 13:34' },
  { text: 'You do not stay angry forever but delight to show mercy.', ref: 'Micah 7:18' },

  // ── Faith & trust ───────────────────────────────────────────────────────────
  { text: 'Fixing our eyes on Jesus, the pioneer and perfecter of faith.', ref: 'Hebrews 12:2' },
  { text: 'In all your ways submit to him, and he will make your paths straight.', ref: 'Proverbs 3:6' },
  { text: 'Commit your way to the Lord; trust in him and he will do this.', ref: 'Psalm 37:5' },
  { text: 'Jesus Christ is the same yesterday and today and forever.', ref: 'Hebrews 13:8' },
  { text: 'If you have faith as small as a mustard seed, nothing will be impossible for you.', ref: 'Matthew 17:20' },
  { text: 'So we fix our eyes not on what is seen, but on what is unseen, since what is unseen is eternal.', ref: '2 Corinthians 4:18' },
  { text: 'Those who know your name trust in you, for you, Lord, have never forsaken those who seek you.', ref: 'Psalm 9:10' },
  { text: 'I keep my eyes always on the Lord. With him at my right hand, I will not be shaken.', ref: 'Psalm 16:8' },

  // ── Guidance & wisdom ───────────────────────────────────────────────────────
  { text: 'If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault.', ref: 'James 1:5' },
  { text: 'Commit to the Lord whatever you do, and he will establish your plans.', ref: 'Proverbs 16:3' },
  { text: 'I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.', ref: 'Psalm 32:8' },
  { text: 'Whether you turn to the right or to the left, your ears will hear a voice saying, This is the way; walk in it.', ref: 'Isaiah 30:21' },
  { text: 'For the Lord gives wisdom; from his mouth come knowledge and understanding.', ref: 'Proverbs 2:6' },
  { text: 'Show me your ways, Lord, teach me your paths.', ref: 'Psalm 25:4' },
  { text: 'I lift up my eyes to the mountains — where does my help come from? My help comes from the Lord.', ref: 'Psalm 121:1–2' },

  // ── Joy & gratitude ─────────────────────────────────────────────────────────
  { text: 'This is the day that the Lord has made; let us rejoice and be glad in it.', ref: 'Psalm 118:24' },
  { text: 'Rejoice always, pray continually, give thanks in all circumstances.', ref: '1 Thessalonians 5:16–18' },
  { text: 'Rejoice in the Lord always. I will say it again: Rejoice!', ref: 'Philippians 4:4' },
  { text: 'You make known to me the path of life; you will fill me with joy in your presence.', ref: 'Psalm 16:11' },
  { text: 'Enter his gates with thanksgiving and his courts with praise; give thanks to him and praise his name.', ref: 'Psalm 100:4' },
  { text: 'Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds.', ref: 'James 1:2' },

  // ── Provision & care ────────────────────────────────────────────────────────
  { text: 'And my God will meet all your needs according to the riches of his glory in Christ Jesus.', ref: 'Philippians 4:19' },
  { text: 'But seek first his kingdom and his righteousness, and all these things will be given to you as well.', ref: 'Matthew 6:33' },
  { text: 'Those who seek the Lord lack no good thing.', ref: 'Psalm 34:10' },
  { text: 'No good thing does he withhold from those whose walk is blameless.', ref: 'Psalm 84:11' },
  { text: 'Look at the birds of the air; your heavenly Father feeds them. Are you not much more valuable than they?', ref: 'Matthew 6:26' },
  { text: 'The Lord is good to all; he has compassion on all he has made.', ref: 'Psalm 145:9' },

  // ── Identity & worth ────────────────────────────────────────────────────────
  { text: 'I praise you because I am fearfully and wonderfully made; your works are wonderful.', ref: 'Psalm 139:14' },
  { text: 'For we are God’s handiwork, created in Christ Jesus to do good works.', ref: 'Ephesians 2:10' },
  { text: 'But you are a chosen people, a royal priesthood, a holy nation, God’s special possession.', ref: '1 Peter 2:9' },
  { text: 'Do not fear, for I have redeemed you; I have summoned you by name; you are mine.', ref: 'Isaiah 43:1' },
  { text: 'Before I formed you in the womb I knew you, before you were born I set you apart.', ref: 'Jeremiah 1:5' },
  { text: 'Yet to all who did receive him, he gave the right to become children of God.', ref: 'John 1:12' },
  { text: 'I have been crucified with Christ and I no longer live, but Christ lives in me.', ref: 'Galatians 2:20' },

  // ── Forgiveness & renewal ───────────────────────────────────────────────────
  { text: 'If we confess our sins, he is faithful and just and will forgive us our sins.', ref: '1 John 1:9' },
  { text: 'Create in me a pure heart, O God, and renew a steadfast spirit within me.', ref: 'Psalm 51:10' },
  { text: 'Though your sins are like scarlet, they shall be as white as snow.', ref: 'Isaiah 1:18' },
  { text: 'As far as the east is from the west, so far has he removed our transgressions from us.', ref: 'Psalm 103:12' },
  { text: 'I will give you a new heart and put a new spirit in you.', ref: 'Ezekiel 36:26' },
  { text: 'Repent, then, and turn to God, so that your sins may be wiped out.', ref: 'Acts 3:19' },

  // ── Endurance & perseverance ────────────────────────────────────────────────
  { text: 'Blessed is the one who perseveres under trial because, having stood the test, that person will receive the crown of life.', ref: 'James 1:12' },
  { text: 'Suffering produces perseverance; perseverance, character; and character, hope.', ref: 'Romans 5:3–4' },
  { text: 'Therefore we do not lose heart. Though outwardly we are wasting away, yet inwardly we are being renewed day by day.', ref: '2 Corinthians 4:16' },
  { text: 'Let us run with perseverance the race marked out for us.', ref: 'Hebrews 12:1' },
  { text: 'Wait for the Lord; be strong and take heart and wait for the Lord.', ref: 'Psalm 27:14' },
  { text: 'I consider that our present sufferings are not worth comparing with the glory that will be revealed in us.', ref: 'Romans 8:18' },
  { text: 'Always give yourselves fully to the work of the Lord, because your labor in the Lord is not in vain.', ref: '1 Corinthians 15:58' },

  // ── Presence & protection ───────────────────────────────────────────────────
  { text: 'Whoever dwells in the shelter of the Most High will rest in the shadow of the Almighty.', ref: 'Psalm 91:1' },
  { text: 'And surely I am with you always, to the very end of the age.', ref: 'Matthew 28:20' },
  { text: 'You are my hiding place; you will protect me from trouble and surround me with songs of deliverance.', ref: 'Psalm 32:7' },
  { text: 'When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you.', ref: 'Isaiah 43:2' },
  { text: 'The Lord will keep you from all harm — he will watch over your life.', ref: 'Psalm 121:7' },
  { text: 'The name of the Lord is a fortified tower; the righteous run to it and are safe.', ref: 'Proverbs 18:10' },
  { text: 'The eternal God is your refuge, and underneath are the everlasting arms.', ref: 'Deuteronomy 33:27' },

  // ── More Psalms ─────────────────────────────────────────────────────────────
  { text: 'That person is like a tree planted by streams of water, which yields its fruit in season.', ref: 'Psalm 1:3' },
  { text: 'But you, Lord, are a shield around me, my glory, the One who lifts my head high.', ref: 'Psalm 3:3' },
  { text: 'In the morning, Lord, you hear my voice; in the morning I lay my requests before you and wait expectantly.', ref: 'Psalm 5:3' },
  { text: 'When I consider your heavens, the work of your fingers — what is mankind that you are mindful of them?', ref: 'Psalm 8:3–4' },
  { text: 'But I trust in your unfailing love; my heart rejoices in your salvation.', ref: 'Psalm 13:5' },
  { text: 'Keep me safe, my God, for in you I take refuge.', ref: 'Psalm 16:1' },
  { text: 'The heavens declare the glory of God; the skies proclaim the work of his hands.', ref: 'Psalm 19:1' },
  { text: 'May these words of my mouth and this meditation of my heart be pleasing in your sight, Lord.', ref: 'Psalm 19:14' },
  { text: 'Some trust in chariots and some in horses, but we trust in the name of the Lord our God.', ref: 'Psalm 20:7' },
  { text: 'Guide me in your truth and teach me, for you are God my Savior, and my hope is in you all day long.', ref: 'Psalm 25:5' },
  { text: 'One thing I ask from the Lord: that I may dwell in the house of the Lord all the days of my life.', ref: 'Psalm 27:4' },
  { text: 'My heart says of you, Seek his face! Your face, Lord, I will seek.', ref: 'Psalm 27:8' },
  { text: 'I remain confident of this: I will see the goodness of the Lord in the land of the living.', ref: 'Psalm 27:13' },
  { text: 'The Lord gives strength to his people; the Lord blesses his people with peace.', ref: 'Psalm 29:11' },
  { text: 'Since you are my rock and my fortress, for the sake of your name lead and guide me.', ref: 'Psalm 31:3' },
  { text: 'For the word of the Lord is right and true; he is faithful in all he does.', ref: 'Psalm 33:4' },
  { text: 'We wait in hope for the Lord; he is our help and our shield.', ref: 'Psalm 33:20' },
  { text: 'May your unfailing love be with us, Lord, even as we put our hope in you.', ref: 'Psalm 33:22' },
  { text: 'I will extol the Lord at all times; his praise will always be on my lips.', ref: 'Psalm 34:1' },
  { text: 'Taste and see that the Lord is good; blessed is the one who takes refuge in him.', ref: 'Psalm 34:8' },
  { text: 'The righteous person may have many troubles, but the Lord delivers him from them all.', ref: 'Psalm 34:19' },
  { text: 'Be still before the Lord and wait patiently for him.', ref: 'Psalm 37:7' },
  { text: 'The Lord makes firm the steps of the one who delights in him.', ref: 'Psalm 37:23' },
  { text: 'I waited patiently for the Lord; he turned to me and heard my cry.', ref: 'Psalm 40:1' },
  { text: 'He lifted me out of the slimy pit; he set my feet on a rock and gave me a firm place to stand.', ref: 'Psalm 40:2' },
  { text: 'As the deer pants for streams of water, so my soul pants for you, my God.', ref: 'Psalm 42:1' },
  { text: 'Why, my soul, are you downcast? Put your hope in God, for I will yet praise him.', ref: 'Psalm 42:11' },
  { text: 'God is within her, she will not fall; God will help her at break of day.', ref: 'Psalm 46:5' },
  { text: 'For this God is our God for ever and ever; he will be our guide even to the end.', ref: 'Psalm 48:14' },
  { text: 'Restore to me the joy of your salvation and grant me a willing spirit, to sustain me.', ref: 'Psalm 51:12' },
  { text: 'Evening, morning and noon I cry out in distress, and he hears my voice.', ref: 'Psalm 55:17' },
  { text: 'You keep track of all my sorrows. You have collected all my tears in your bottle.', ref: 'Psalm 56:8' },
  { text: 'But I will sing of your strength, in the morning I will sing of your love.', ref: 'Psalm 59:16' },
  { text: 'From the ends of the earth I call to you; lead me to the rock that is higher than I.', ref: 'Psalm 61:2' },
  { text: 'Yes, my soul, find rest in God; my hope comes from him.', ref: 'Psalm 62:5' },
  { text: 'Trust in him at all times, you people; pour out your hearts to him, for God is our refuge.', ref: 'Psalm 62:8' },
  { text: 'You, God, are my God, earnestly I seek you; I thirst for you, my whole being longs for you.', ref: 'Psalm 63:1' },
  { text: 'Because your love is better than life, my lips will glorify you.', ref: 'Psalm 63:3' },
  { text: 'Praise be to the Lord, to God our Savior, who daily bears our burdens.', ref: 'Psalm 68:19' },
  { text: 'As for me, I will always have hope; I will praise you more and more.', ref: 'Psalm 71:14' },
  { text: 'Yet I am always with you; you hold me by my right hand.', ref: 'Psalm 73:23' },
  { text: 'But as for me, it is good to be near God. I have made the Sovereign Lord my refuge.', ref: 'Psalm 73:28' },
  { text: 'Better is one day in your courts than a thousand elsewhere.', ref: 'Psalm 84:10' },
  { text: 'You, Lord, are forgiving and good, abounding in love to all who call to you.', ref: 'Psalm 86:5' },
  { text: 'Teach me your way, Lord, that I may rely on your faithfulness.', ref: 'Psalm 86:11' },
  { text: 'But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love and faithfulness.', ref: 'Psalm 86:15' },
  { text: 'I will sing of the Lord’s great love forever; with my mouth I will make your faithfulness known.', ref: 'Psalm 89:1' },
  { text: 'From everlasting to everlasting you are God.', ref: 'Psalm 90:2' },
  { text: 'Teach us to number our days, that we may gain a heart of wisdom.', ref: 'Psalm 90:12' },
  { text: 'Satisfy us in the morning with your unfailing love, that we may sing for joy and be glad all our days.', ref: 'Psalm 90:14' },
  { text: 'He will cover you with his feathers, and under his wings you will find refuge.', ref: 'Psalm 91:4' },
  { text: 'For he will command his angels concerning you to guard you in all your ways.', ref: 'Psalm 91:11' },
  { text: 'When I said, My foot is slipping, your unfailing love, Lord, supported me.', ref: 'Psalm 94:18' },
  { text: 'Come, let us bow down in worship, let us kneel before the Lord our Maker.', ref: 'Psalm 95:6' },
  { text: 'For the Lord is good and his love endures forever; his faithfulness continues through all generations.', ref: 'Psalm 100:5' },
  { text: 'Praise the Lord, my soul; all my inmost being, praise his holy name.', ref: 'Psalm 103:1' },
  { text: 'Praise the Lord, my soul, and forget not all his benefits.', ref: 'Psalm 103:2' },
  { text: 'The Lord is compassionate and gracious, slow to anger, abounding in love.', ref: 'Psalm 103:8' },
  { text: 'As a father has compassion on his children, so the Lord has compassion on those who fear him.', ref: 'Psalm 103:13' },
  { text: 'Look to the Lord and his strength; seek his face always.', ref: 'Psalm 105:4' },
  { text: 'Give thanks to the Lord, for he is good; his love endures forever.', ref: 'Psalm 107:1' },
  { text: 'They will have no fear of bad news; their hearts are steadfast, trusting in the Lord.', ref: 'Psalm 112:7' },
  { text: 'I love the Lord, for he heard my voice; he heard my cry for mercy.', ref: 'Psalm 116:1' },
  { text: 'The Lord is with me; I will not be afraid. What can mere mortals do to me?', ref: 'Psalm 118:6' },
  { text: 'It is better to take refuge in the Lord than to trust in humans.', ref: 'Psalm 118:8' },
  { text: 'I have hidden your word in my heart that I might not sin against you.', ref: 'Psalm 119:11' },
  { text: 'My comfort in my suffering is this: Your promise preserves my life.', ref: 'Psalm 119:50' },
  { text: 'You are my refuge and my shield; I have put my hope in your word.', ref: 'Psalm 119:114' },
  { text: 'He will not let your foot slip — he who watches over you will not slumber.', ref: 'Psalm 121:3' },
  { text: 'The Lord watches over you — the Lord is your shade at your right hand.', ref: 'Psalm 121:5' },
  { text: 'Those who sow with tears will reap with songs of joy.', ref: 'Psalm 126:5' },
  { text: 'Unless the Lord builds the house, the builders labor in vain.', ref: 'Psalm 127:1' },
  { text: 'Put your hope in the Lord, for with the Lord is unfailing love and with him is full redemption.', ref: 'Psalm 130:7' },
  { text: 'How good and pleasant it is when God’s people live together in unity!', ref: 'Psalm 133:1' },
  { text: 'When I called, you answered me; you greatly emboldened me.', ref: 'Psalm 138:3' },
  { text: 'Though I walk in the midst of trouble, you preserve my life.', ref: 'Psalm 138:7' },
  { text: 'You hem me in behind and before, and you lay your hand upon me.', ref: 'Psalm 139:5' },
  { text: 'Even there your hand will guide me, your right hand will hold me fast.', ref: 'Psalm 139:10' },
  { text: 'Search me, God, and know my heart; test me and know my anxious thoughts.', ref: 'Psalm 139:23' },
  { text: 'Let the morning bring me word of your unfailing love, for I have put my trust in you.', ref: 'Psalm 143:8' },
  { text: 'Teach me to do your will, for you are my God; may your good Spirit lead me on level ground.', ref: 'Psalm 143:10' },
  { text: 'The Lord is gracious and compassionate, slow to anger and rich in love.', ref: 'Psalm 145:8' },
  { text: 'The Lord is near to all who call on him, to all who call on him in truth.', ref: 'Psalm 145:18' },
  { text: 'Blessed are those whose help is the God of Jacob, whose hope is in the Lord their God.', ref: 'Psalm 146:5' },

  // ── More Proverbs ───────────────────────────────────────────────────────────
  { text: 'The fear of the Lord is the beginning of knowledge.', ref: 'Proverbs 1:7' },
  { text: 'Do not be wise in your own eyes; fear the Lord and shun evil.', ref: 'Proverbs 3:7' },
  { text: 'Above all else, guard your heart, for everything you do flows from it.', ref: 'Proverbs 4:23' },
  { text: 'A generous person will prosper; whoever refreshes others will be refreshed.', ref: 'Proverbs 11:25' },
  { text: 'A gentle answer turns away wrath, but a harsh word stirs up anger.', ref: 'Proverbs 15:1' },
  { text: 'In their hearts humans plan their course, but the Lord establishes their steps.', ref: 'Proverbs 16:9' },
  { text: 'A friend loves at all times, and a brother is born for a time of adversity.', ref: 'Proverbs 17:17' },
  { text: 'A cheerful heart is good medicine, but a crushed spirit dries up the bones.', ref: 'Proverbs 17:22' },
  { text: 'Many are the plans in a person’s heart, but it is the Lord’s purpose that prevails.', ref: 'Proverbs 19:21' },
  { text: 'Start children off on the way they should go, and even when they are old they will not turn from it.', ref: 'Proverbs 22:6' },
  { text: 'As iron sharpens iron, so one person sharpens another.', ref: 'Proverbs 27:17' },
  { text: 'Whoever conceals their sins does not prosper, but the one who confesses and renounces them finds mercy.', ref: 'Proverbs 28:13' },

  // ── More Isaiah ─────────────────────────────────────────────────────────────
  { text: 'For to us a child is born, to us a son is given; and he will be called Wonderful Counselor, Mighty God, Prince of Peace.', ref: 'Isaiah 9:6' },
  { text: 'Surely God is my salvation; I will trust and not be afraid. The Lord is my strength and my defense.', ref: 'Isaiah 12:2' },
  { text: 'Lord, you are my God; I will exalt you and praise your name, for in perfect faithfulness you have done wonderful things.', ref: 'Isaiah 25:1' },
  { text: 'Trust in the Lord forever, for the Lord, the Lord himself, is the Rock eternal.', ref: 'Isaiah 26:4' },
  { text: 'In repentance and rest is your salvation, in quietness and trust is your strength.', ref: 'Isaiah 30:15' },
  { text: 'The fruit of that righteousness will be peace; its effect will be quietness and confidence forever.', ref: 'Isaiah 32:17' },
  { text: 'The grass withers and the flowers fall, but the word of our God endures forever.', ref: 'Isaiah 40:8' },
  { text: 'He tends his flock like a shepherd: He gathers the lambs in his arms and carries them close to his heart.', ref: 'Isaiah 40:11' },
  { text: 'I, even I, am he who blots out your transgressions, and remembers your sins no more.', ref: 'Isaiah 43:25' },
  { text: 'Even to your old age and gray hairs I am he, I am he who will sustain you.', ref: 'Isaiah 46:4' },
  { text: 'See, I have engraved you on the palms of my hands.', ref: 'Isaiah 49:16' },
  { text: 'But he was pierced for our transgressions, he was crushed for our iniquities; by his wounds we are healed.', ref: 'Isaiah 53:5' },
  { text: 'Though the mountains be shaken and the hills be removed, yet my unfailing love for you will not be shaken.', ref: 'Isaiah 54:10' },
  { text: 'For my thoughts are not your thoughts, neither are your ways my ways, declares the Lord.', ref: 'Isaiah 55:8' },
  { text: 'So is my word that goes out from my mouth: It will not return to me empty.', ref: 'Isaiah 55:11' },
  { text: 'The Lord will guide you always; he will satisfy your needs in a sun-scorched land.', ref: 'Isaiah 58:11' },
  { text: 'The Spirit of the Sovereign Lord is on me, to bind up the brokenhearted, to proclaim freedom for the captives.', ref: 'Isaiah 61:1' },
  { text: 'Yet you, Lord, are our Father. We are the clay, you are the potter; we are all the work of your hand.', ref: 'Isaiah 64:8' },

  // ── Gospels ─────────────────────────────────────────────────────────────────
  { text: 'Blessed are those who hunger and thirst for righteousness, for they will be filled.', ref: 'Matthew 5:6' },
  { text: 'Blessed are the peacemakers, for they will be called children of God.', ref: 'Matthew 5:9' },
  { text: 'You are the light of the world. A town built on a hill cannot be hidden.', ref: 'Matthew 5:14' },
  { text: 'Let your light shine before others, that they may see your good deeds and glorify your Father in heaven.', ref: 'Matthew 5:16' },
  { text: 'For if you forgive other people when they sin against you, your heavenly Father will also forgive you.', ref: 'Matthew 6:14' },
  { text: 'For where your treasure is, there your heart will be also.', ref: 'Matthew 6:21' },
  { text: 'So in everything, do to others what you would have them do to you.', ref: 'Matthew 7:12' },
  { text: 'Take my yoke upon you and learn from me, for I am gentle and humble in heart, and you will find rest for your souls.', ref: 'Matthew 11:29' },
  { text: 'For where two or three gather in my name, there am I with them.', ref: 'Matthew 18:20' },
  { text: 'With man this is impossible, but with God all things are possible.', ref: 'Matthew 19:26' },
  { text: 'Love the Lord your God with all your heart and with all your soul and with all your mind.', ref: 'Matthew 22:37' },
  { text: 'Therefore go and make disciples of all nations.', ref: 'Matthew 28:19' },
  { text: 'Everything is possible for one who believes.', ref: 'Mark 9:23' },
  { text: 'Love your neighbor as yourself. There is no commandment greater than these.', ref: 'Mark 12:31' },
  { text: 'Whatever you ask for in prayer, believe that you have received it, and it will be yours.', ref: 'Mark 11:24' },
  { text: 'For no word from God will ever fail.', ref: 'Luke 1:37' },
  { text: 'Give, and it will be given to you. A good measure, pressed down, shaken together and running over.', ref: 'Luke 6:38' },
  { text: 'Indeed, the very hairs of your head are all numbered. Don’t be afraid; you are worth more than many sparrows.', ref: 'Luke 12:7' },
  { text: 'The light shines in the darkness, and the darkness has not overcome it.', ref: 'John 1:5' },
  { text: 'Whoever drinks the water I give them will never thirst.', ref: 'John 4:14' },
  { text: 'I am the bread of life. Whoever comes to me will never go hungry.', ref: 'John 6:35' },
  { text: 'I am the light of the world. Whoever follows me will never walk in darkness, but will have the light of life.', ref: 'John 8:12' },
  { text: 'Then you will know the truth, and the truth will set you free.', ref: 'John 8:32' },
  { text: 'I have come that they may have life, and have it to the full.', ref: 'John 10:10' },
  { text: 'I am the good shepherd. The good shepherd lays down his life for the sheep.', ref: 'John 10:11' },
  { text: 'I give them eternal life, and they shall never perish; no one will snatch them out of my hand.', ref: 'John 10:28' },
  { text: 'I am the resurrection and the life. The one who believes in me will live, even though they die.', ref: 'John 11:25' },
  { text: 'Do not let your hearts be troubled. You believe in God; believe also in me.', ref: 'John 14:1' },
  { text: 'My Father’s house has many rooms; I am going there to prepare a place for you.', ref: 'John 14:2' },
  { text: 'I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit.', ref: 'John 15:5' },
  { text: 'Blessed are those who have not seen and yet have believed.', ref: 'John 20:29' },

  // ── Acts & Paul’s letters ───────────────────────────────────────────────────
  { text: 'Believe in the Lord Jesus, and you will be saved.', ref: 'Acts 16:31' },
  { text: 'My only aim is to finish the race and complete the task the Lord Jesus has given me.', ref: 'Acts 20:24' },
  { text: 'For I am not ashamed of the gospel, because it is the power of God that brings salvation to everyone who believes.', ref: 'Romans 1:16' },
  { text: 'For all have sinned and fall short of the glory of God.', ref: 'Romans 3:23' },
  { text: 'For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.', ref: 'Romans 6:23' },
  { text: 'If you declare with your mouth Jesus is Lord, and believe in your heart that God raised him from the dead, you will be saved.', ref: 'Romans 10:9' },
  { text: 'For everyone who calls on the name of the Lord will be saved.', ref: 'Romans 10:13' },
  { text: 'Do not conform to the pattern of this world, but be transformed by the renewing of your mind.', ref: 'Romans 12:2' },
  { text: 'Accept one another, then, just as Christ accepted you, in order to bring praise to God.', ref: 'Romans 15:7' },
  { text: 'God is faithful, who has called you into fellowship with his Son, Jesus Christ our Lord.', ref: '1 Corinthians 1:9' },
  { text: 'What no eye has seen, what no ear has heard, the things God has prepared for those who love him.', ref: '1 Corinthians 2:9' },
  { text: 'God is faithful; he will not let you be tempted beyond what you can bear.', ref: '1 Corinthians 10:13' },
  { text: 'Love always protects, always trusts, always hopes, always perseveres.', ref: '1 Corinthians 13:7' },
  { text: 'But thanks be to God! He gives us the victory through our Lord Jesus Christ.', ref: '1 Corinthians 15:57' },
  { text: 'Do everything in love.', ref: '1 Corinthians 16:14' },
  { text: 'Praise be to the God of all comfort, who comforts us in all our troubles.', ref: '2 Corinthians 1:3' },
  { text: 'Now the Lord is the Spirit, and where the Spirit of the Lord is, there is freedom.', ref: '2 Corinthians 3:17' },
  { text: 'Each of you should give what you have decided in your heart to give, for God loves a cheerful giver.', ref: '2 Corinthians 9:7' },
  { text: 'And God is able to bless you abundantly, so that you will abound in every good work.', ref: '2 Corinthians 9:8' },
  { text: 'It is for freedom that Christ has set us free.', ref: 'Galatians 5:1' },
  { text: 'But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness.', ref: 'Galatians 5:22' },
  { text: 'Carry each other’s burdens, and in this way you will fulfill the law of Christ.', ref: 'Galatians 6:2' },
  { text: 'In him we have redemption through his blood, the forgiveness of sins, in accordance with the riches of God’s grace.', ref: 'Ephesians 1:7' },
  { text: 'But because of his great love for us, God, who is rich in mercy, made us alive with Christ.', ref: 'Ephesians 2:4' },
  { text: 'Now to him who is able to do immeasurably more than all we ask or imagine, according to his power at work within us.', ref: 'Ephesians 3:20' },
  { text: 'Be completely humble and gentle; be patient, bearing with one another in love.', ref: 'Ephesians 4:2' },
  { text: 'Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you.', ref: 'Ephesians 4:32' },
  { text: 'Being confident of this, that he who began a good work in you will carry it on to completion.', ref: 'Philippians 1:6' },
  { text: 'In humility value others above yourselves, not looking to your own interests but to the interests of others.', ref: 'Philippians 2:3' },
  { text: 'Forgetting what is behind and straining toward what is ahead, I press on toward the goal.', ref: 'Philippians 3:13' },
  { text: 'Whatever is true, whatever is noble, whatever is right, whatever is pure — think about such things.', ref: 'Philippians 4:8' },
  { text: 'I have learned to be content whatever the circumstances.', ref: 'Philippians 4:11' },
  { text: 'Set your minds on things above, not on earthly things.', ref: 'Colossians 3:2' },
  { text: 'Clothe yourselves with compassion, kindness, humility, gentleness and patience.', ref: 'Colossians 3:12' },
  { text: 'Whatever you do, work at it with all your heart, as working for the Lord, not for human masters.', ref: 'Colossians 3:23' },
  { text: 'Therefore encourage one another and build each other up.', ref: '1 Thessalonians 5:11' },
  { text: 'But the Lord is faithful, and he will strengthen you and protect you from the evil one.', ref: '2 Thessalonians 3:3' },

  // ── General letters & Revelation ────────────────────────────────────────────
  { text: 'But godliness with contentment is great gain.', ref: '1 Timothy 6:6' },
  { text: 'I have fought the good fight, I have finished the race, I have kept the faith.', ref: '2 Timothy 4:7' },
  { text: 'Let us then approach God’s throne of grace with confidence, so that we may receive mercy and find grace to help us in our time of need.', ref: 'Hebrews 4:16' },
  { text: 'We have this hope as an anchor for the soul, firm and secure.', ref: 'Hebrews 6:19' },
  { text: 'Let us hold unswervingly to the hope we profess, for he who promised is faithful.', ref: 'Hebrews 10:23' },
  { text: 'And let us consider how we may spur one another on toward love and good deeds.', ref: 'Hebrews 10:24' },
  { text: 'And without faith it is impossible to please God.', ref: 'Hebrews 11:6' },
  { text: 'Never will I leave you; never will I forsake you.', ref: 'Hebrews 13:5' },
  { text: 'Every good and perfect gift is from above, coming down from the Father of the heavenly lights.', ref: 'James 1:17' },
  { text: 'Everyone should be quick to listen, slow to speak and slow to become angry.', ref: 'James 1:19' },
  { text: 'Do not merely listen to the word, and so deceive yourselves. Do what it says.', ref: 'James 1:22' },
  { text: 'Come near to God and he will come near to you.', ref: 'James 4:8' },
  { text: 'The prayer of a righteous person is powerful and effective.', ref: 'James 5:16' },
  { text: 'In his great mercy he has given us new birth into a living hope through the resurrection of Jesus Christ.', ref: '1 Peter 1:3' },
  { text: 'Always be prepared to give an answer to everyone who asks you to give the reason for the hope that you have.', ref: '1 Peter 3:15' },
  { text: 'Humble yourselves, therefore, under God’s mighty hand, that he may lift you up in due time.', ref: '1 Peter 5:6' },
  { text: 'And the God of all grace will himself restore you and make you strong, firm and steadfast.', ref: '1 Peter 5:10' },
  { text: 'The Lord is patient with you, not wanting anyone to perish, but everyone to come to repentance.', ref: '2 Peter 3:9' },
  { text: 'See what great love the Father has lavished on us, that we should be called children of God!', ref: '1 John 3:1' },
  { text: 'Dear friends, let us love one another, for love comes from God.', ref: '1 John 4:7' },
  { text: 'This is the confidence we have in approaching God: that if we ask anything according to his will, he hears us.', ref: '1 John 5:14' },
  { text: 'To him who is able to keep you from stumbling and to present you before his glorious presence without fault and with great joy.', ref: 'Jude 1:24' },
  { text: 'Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in.', ref: 'Revelation 3:20' },
  { text: 'He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain.', ref: 'Revelation 21:4' },
  { text: 'He who was seated on the throne said, I am making everything new!', ref: 'Revelation 21:5' },

  // ── Across the Old Testament ────────────────────────────────────────────────
  { text: 'In the beginning God created the heavens and the earth.', ref: 'Genesis 1:1' },
  { text: 'I am with you and will watch over you wherever you go.', ref: 'Genesis 28:15' },
  { text: 'You intended to harm me, but God intended it for good.', ref: 'Genesis 50:20' },
  { text: 'The Lord will fight for you; you need only to be still.', ref: 'Exodus 14:14' },
  { text: 'The Lord is my strength and my defense; he has become my salvation.', ref: 'Exodus 15:2' },
  { text: 'My Presence will go with you, and I will give you rest.', ref: 'Exodus 33:14' },
  { text: 'The Lord bless you and keep you; the Lord make his face shine on you and be gracious to you.', ref: 'Numbers 6:24–25' },
  { text: 'Love the Lord your God with all your heart and with all your soul and with all your strength.', ref: 'Deuteronomy 6:5' },
  { text: 'Know therefore that the Lord your God is God; he is the faithful God, keeping his covenant of love.', ref: 'Deuteronomy 7:9' },
  { text: 'Be strong and courageous, for the Lord your God goes with you; he will never leave you nor forsake you.', ref: 'Deuteronomy 31:6' },
  { text: 'The Lord does not look at the things people look at; the Lord looks at the heart.', ref: '1 Samuel 16:7' },
  { text: 'If my people, who are called by my name, will humble themselves and pray, I will hear from heaven.', ref: '2 Chronicles 7:14' },
  { text: 'Do not be afraid or discouraged, for the battle is not yours, but God’s.', ref: '2 Chronicles 20:15' },
  { text: 'But you are a forgiving God, gracious and compassionate, slow to anger and abounding in love.', ref: 'Nehemiah 9:17' },
  { text: 'I know that my redeemer lives, and that in the end he will stand on the earth.', ref: 'Job 19:25' },
  { text: 'But he knows the way that I take; when he has tested me, I will come forth as gold.', ref: 'Job 23:10' },
  { text: 'There is a time for everything, and a season for every activity under the heavens.', ref: 'Ecclesiastes 3:1' },
  { text: 'Two are better than one. If either of them falls down, one can help the other up.', ref: 'Ecclesiastes 4:9–10' },
  { text: 'I have loved you with an everlasting love; I have drawn you with unfailing kindness.', ref: 'Jeremiah 31:3' },
  { text: 'Call to me and I will answer you and tell you great and unsearchable things you do not know.', ref: 'Jeremiah 33:3' },
  { text: 'The Lord is good to those whose hope is in him, to the one who seeks him.', ref: 'Lamentations 3:25' },
  { text: 'And what does the Lord require of you? To act justly and to love mercy and to walk humbly with your God.', ref: 'Micah 6:8' },
  { text: 'The Lord is good, a refuge in times of trouble. He cares for those who trust in him.', ref: 'Nahum 1:7' },
  { text: 'Though it linger, wait for it; it will certainly come and will not delay.', ref: 'Habakkuk 2:3' },
  { text: 'Not by might nor by power, but by my Spirit, says the Lord Almighty.', ref: 'Zechariah 4:6' },
  { text: 'I the Lord do not change.', ref: 'Malachi 3:6' },

  // ── Final set — to 400 (so the cycle drifts year to year) ───────────────────
  { text: 'He makes me lie down in green pastures, he leads me beside quiet waters.', ref: 'Psalm 23:2' },
  { text: 'He refreshes my soul. He guides me along the right paths for his name’s sake.', ref: 'Psalm 23:3' },
  { text: 'I will say of the Lord, He is my refuge and my fortress, my God, in whom I trust.', ref: 'Psalm 91:2' },
  { text: 'The Lord will watch over your coming and going both now and forevermore.', ref: 'Psalm 121:8' },
  { text: 'Where can I go from your Spirit? Where can I flee from your presence?', ref: 'Psalm 139:7' },
  { text: 'Though he may stumble, he will not fall, for the Lord upholds him with his hand.', ref: 'Psalm 37:24' },
  { text: 'But I trust in you, Lord; I say, You are my God.', ref: 'Psalm 31:14' },
  { text: 'I love you, Lord, my strength.', ref: 'Psalm 18:1' },
  { text: 'And call on me in the day of trouble; I will deliver you, and you will honor me.', ref: 'Psalm 50:15' },
  { text: 'Gracious words are a honeycomb, sweet to the soul and healing to the bones.', ref: 'Proverbs 16:24' },
  { text: 'Anxiety weighs down the heart, but a kind word cheers it up.', ref: 'Proverbs 12:25' },
  { text: 'She is clothed with strength and dignity; she can laugh at the days to come.', ref: 'Proverbs 31:25' },
  { text: 'The Lord is the everlasting God, the Creator of the ends of the earth. He will not grow tired or weary.', ref: 'Isaiah 40:28' },
  { text: 'Be strong, do not fear; your God will come.', ref: 'Isaiah 35:4' },
  { text: 'Blessed are the merciful, for they will be shown mercy.', ref: 'Matthew 5:7' },
  { text: 'Your Father knows what you need before you ask him.', ref: 'Matthew 6:8' },
  { text: 'If you believe, you will receive whatever you ask for in prayer.', ref: 'Matthew 21:22' },
  { text: 'My soul glorifies the Lord and my spirit rejoices in God my Savior.', ref: 'Luke 1:46–47' },
  { text: 'You do not realize now what I am doing, but later you will understand.', ref: 'John 13:7' },
  { text: 'Now this is eternal life: that they know you, the only true God, and Jesus Christ, whom you have sent.', ref: 'John 17:3' },
  { text: 'The Spirit helps us in our weakness; the Spirit himself intercedes for us.', ref: 'Romans 8:26' },
  { text: 'No, in all these things we are more than conquerors through him who loved us.', ref: 'Romans 8:37' },
  { text: 'For from him and through him and for him are all things. To him be the glory forever!', ref: 'Romans 11:36' },
  { text: 'Do not be overcome by evil, but overcome evil with good.', ref: 'Romans 12:21' },
  { text: 'Walk in the way of love, just as Christ loved us and gave himself up for us.', ref: 'Ephesians 5:2' },
  { text: 'For to me, to live is Christ and to die is gain.', ref: 'Philippians 1:21' },
  { text: 'He is before all things, and in him all things hold together.', ref: 'Colossians 1:17' },
  { text: 'Continue to live your lives in him, rooted and built up in him, strengthened in the faith.', ref: 'Colossians 2:7' },
  { text: 'The one who calls you is faithful, and he will do it.', ref: '1 Thessalonians 5:24' },
  { text: 'For the word of God is alive and active, sharper than any double-edged sword.', ref: 'Hebrews 4:12' },
  { text: 'Peacemakers who sow in peace reap a harvest of righteousness.', ref: 'James 3:18' },
  { text: 'Each of you should use whatever gift you have received to serve others.', ref: '1 Peter 4:10' },
  { text: 'The world and its desires pass away, but whoever does the will of God lives forever.', ref: '1 John 2:17' },
  { text: 'I am the Alpha and the Omega, the First and the Last, the Beginning and the End.', ref: 'Revelation 22:13' },
];

export function getDailyVerse() {
  const d = new Date();
  const dayKey = d.getFullYear() * 366 + d.getMonth() * 31 + d.getDate();
  return DAILY_VERSES[dayKey % DAILY_VERSES.length];
}

export function getTodayKey() {
  const d = new Date();
  return `${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`;
}

export function getYesterdayKey() {
  const d = new Date();
  d.setDate(d.getDate() - 1);
  return `${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`;
}
